import Head from 'next/head'
import { Fragment, useEffect, useState } from 'react'

export default function Home() {
    const [ students, setStudents ] = useState([]);
    const [ name, setName ] = useState(true);
    const [ email, setEmail ] = useState(true);
    const [ age, setAge ] = useState(true);
    const [ country, setCountry ] = useState(true);
    const [ city, setCity ] = useState(true);

    useEffect(() => {
        const getPageData = async () => {
            const apiUrlEndpoint = `http://localhost:3000/api/student`;
            const response = await fetch(apiUrlEndpoint);
            const students = await response.json();
            setStudents(students);
        }
        getPageData();
    }, []);
    console.log(city)
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='pt-32'>
        <div className='w-full rounded-lg'>
          <h1 className="mb-4 text-2xl font-semibold text-gray-900 dark:text-gray-800">Check your preferable field</h1>
          
          <ul className="items-center w-full text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 sm:flex dark:bg-gray-700 dark:border-gray-600 dark:text-white">
              <li className="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                  <div className="flex items-center pl-3">
                      <input onClick={()=> setName(!name)}  id="vue-checkbox-list" type="checkbox" checked={name} value="name" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                      <label htmlFor="vue-checkbox-list" className="py-3 ml-2 w-full text-sm font-medium text-gray-900 dark:text-gray-300">Name</label>
                  </div>
              </li>
              <li 
                className="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                  <div className="flex items-center pl-3">
                      <input onClick={()=> setEmail(!email)}  id="react-checkbox-list" type="checkbox" checked={email} value="email" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                      <label htmlFor="react-checkbox-list" className="py-4 ml-2 w-full text-sm font-medium text-gray-900 dark:text-gray-300">Email</label>
                  </div>
              </li>
              <li
                className="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                  <div className="flex items-center pl-3">
                      <input onClick={()=> setAge(!age)}  id="js-checkbox-list"  type="checkbox" checked={age} value="age" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                      <label htmlFor="js-checkbox-list" className="py-4 ml-2 w-full text-sm font-medium text-gray-900 dark:text-gray-300">Age</label>
                  </div>
              </li>
              <li 
                className="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                  <div className="flex items-center pl-3">
                      <input onClick={()=> setCountry(!country)} id="angular-checkbox-list" type="checkbox" checked={country} value="country" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                      <label htmlFor="angular-checkbox-list" className="py-4 ml-2 w-full text-sm font-medium text-gray-900 dark:text-gray-300">Country</label>
                  </div>
              </li>
              <li 
                className="w-full dark:border-gray-600">
                  <div className="flex items-center pl-3">
                      <input onClick={()=> setCity(!city)} id="laravel-checkbox-list" type="checkbox" checked={city} value="city" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                      <label htmlFor="laravel-checkbox-list" className="py-4 ml-2 w-full text-sm font-medium text-gray-900 dark:text-gray-300">City</label>
                  </div>
              </li>
          </ul>
        </div>

        <div className='mt-8'>
            <div className="overflow-hidden relative shadow-md sm:rounded-lg">
                <table className="block w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            { email ? (
                                <th scope="col" className="py-3 px-6">
                                    Email
                                </th>
                                ) : ''
                            }
                            
                            { name ? (
                                <th scope="col" className="py-4 px-6">
                                    <div className="flex items-center">
                                        Name
                                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" className="ml-1 w-3 h-3" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"></path></svg></a>
                                    </div>
                                </th>
                                ) : ''

                            }

                            { age ? (
                                <th scope="col" className="py-4 px-6">
                                    <div className="flex items-center">
                                        Age
                                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" className="ml-1 w-3 h-3" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"></path></svg></a>
                                    </div>
                                </th>
                                ) : ''

                            }

                            { country ? (
                                <th scope="col" className="py-4 px-6">
                                    <div className="flex items-center">
                                        Country
                                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" className="ml-1 w-3 h-3" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"></path></svg></a>
                                    </div>
                                </th>
                                ) : ''
                            }
                          
                            {city ? (
                                <th scope="col" className="py-4 px-6">
                                    <div className="flex items-center">
                                    City
                                    <a href="#"><svg xmlns="http://www.w3.org/2000/svg" className="ml-1 w-3 h-3" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"></path></svg></a>
                                    </div>
                                </th>) : ''
                            }
                            
                          
                      </tr>
                  </thead>

                  <tbody>
                    {students.map((student) => (
                        <tr key={student.id} className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            {email ?
                                (<th scope="row" className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                    {student.email}
                                </th>) : '' 
                            }
                            {name ? (
                                <td className="py-4 px-6">
                                    {student.name}
                                </td>
                            ) : ''}

                            {age ? (
                                <td className="py-4 px-6">
                                    {student.age}
                                </td>
                            ) : ''}

                            {country ? (
                                <td className="py-4 px-6">
                                    {student.country}
                                </td>
                            ) : ''}

                            {city ? (
                                <td className="py-4 px-6">
                                    {student.city}
                                </td>
                            ) : ''}
                            
                        </tr>
                    ))}
                      
                  </tbody>
              </table>
              <div>
                
              </div>
          </div>
        </div>
      </main>
    </div>
  )
}


